#!/bin/bash
python run.py   --dataset FB237 \
                --model EnsembleModel \
                --regularizer N3 \
                --reg 0.0 \
                --optimizer Adagrad \
                --max_epochs 500 \
                --patience 100 \
                --valid 5 \
                --batch_size 8000 \
                --neg_sample_size 100 \
                --init_size 0.001 \
                --learning_rate 0.1 \
                --gamma 0.0 \
                --bias learn \
                --dtype double \
                --multi_c \
                --global_model AttH \
                --global_model_rank 32 \
                --local_model RotH \
                --local_model_rank 32 \
                --KD_iter 40 \
                --KD_SLF_weight 0.8 \
                --KD_EED_weight 0.0 \
                --KD_omega1 0.5 \
                --KD_omega2 0.6 \
                --cuda_id 6
